parameters:
    shift_url_signature.hash_algo: 'SHA256'
    shift_url_signature.secret:    '%env(APP_SECRET)%' # provided by symfony/framework-bundle

services:
    Shift\UrlSignatureBundle\Utils\RequestValidator:
        arguments: ['@request_stack', '@shift_url_signature.validator']

    shift_url_signature.check_request:
        class: Shift\UrlSignatureBundle\EventListener\ControllerCheckRequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController}
        arguments: ['@annotation_reader', '@shift_url_signature.validator']

    shift_url_signature.configuration.default:
        class: UrlSignature\HashConfiguration
        shared: true
        arguments: ['%shift_url_signature.secret%']
        calls:
            -   method: setAlgorithm
                arguments:
                    - '%shift_url_signature.hash_algo%'

    shift_url_signature.builder:
        class:  UrlSignature\Builder
        shared: true
        arguments: ['@shift_url_signature.configuration.default']
        public: true

    UrlSignature\Validator:
        arguments: ['@shift_url_signature.configuration.default']
        shared: true
        public: false

    shift_url_signature.validator:
        alias:  UrlSignature\Validator
        public: true

    Shift\UrlSignatureBundle\Twig\SignedPathExtension:
        arguments: ['@router.default', '@shift_url_signature.builder']
        tags: ['twig.extension']